# Generated by Django 6.0.5 on 2026-06-18 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='desctiption',
            new_name='description',
        ),
    ]
