# Generated by Django 6.0.5 on 2026-06-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_rename_desctiption_plan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='members_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
