# Generated by Django 6.0.5 on 2026-06-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_plan_members_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subcription_item_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
