# Generated by Django 6.0.5 on 2026-08-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_subscription_subcription_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past_Due'), ('canceled', 'Canceled'), ('past_due', 'Past_due')], default='active'),
        ),
    ]
