# Generated by Django 6.0.5 on 2026-08-31 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accepter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_accepter', to=settings.AUTH_USER_MODEL)),
                ('iniciater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_iniciater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'connection_request',
                'constraints': [models.UniqueConstraint(fields=('iniciater', 'accepter'), name='unique_connection_request')],
            },
        ),
    ]
