# Generated by Django 6.0.5 on 2026-08-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='chat_type',
            field=models.CharField(choices=[('Project', 'project'), ('Direct', 'direct')], max_length=200),
        ),
    ]
