# Generated by Django 6.0.5 on 2026-09-01 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_conversation_chat_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='connectionrequest',
            name='unique_connection_request',
        ),
        migrations.RenameField(
            model_name='connectionrequest',
            old_name='accepter',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='connectionrequest',
            old_name='iniciater',
            new_name='sender',
        ),
        migrations.AddConstraint(
            model_name='connectionrequest',
            constraint=models.UniqueConstraint(fields=('sender', 'recipient'), name='unique_connection_request'),
        ),
    ]
