# Generated by Django 6.0.5 on 2026-09-02 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_connectionrequest_recipient_and_more'),
        ('workspace', '0038_alter_activitylog_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_conversation', to='workspace.project'),
        ),
    ]
