# Generated by Django 6.0.5 on 2026-09-04 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_conversation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_status', to='chat.conversation'),
        ),
    ]
