# Generated by Django 6.0.5 on 2026-05-27 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('in_progressin progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='in_progressin progress', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_creator', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='task_members', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_project', to='workspace.project')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_attachment/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploader', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attachment', to='workspace.task')),
            ],
            options={
                'db_table': 'file_attachment',
            },
        ),
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admins', models.ManyToManyField(related_name='workspace_admins', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='workspace_member', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(related_name='workspace_project', to='workspace.project')),
                ('super_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_super_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspace',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='work_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_workspace', to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name='project',
            name='work_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_workspace', to='workspace.workspace'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentor', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_project', to='workspace.project')),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_task', to='workspace.task')),
                ('work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_workspace', to='workspace.workspace')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
