# Generated by Django 6.0.5 on 2026-05-28 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_project_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Task',
            new_name='task',
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_file', to='workspace.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='work_space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_file', to='workspace.workspace'),
            preserve_default=False,
        ),
    ]
