# Generated by Django 6.0.5 on 2026-05-28 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_rename_task_comment_task_fileattachment_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='projects',
        ),
        migrations.AlterField(
            model_name='project',
            name='work_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_project', to='workspace.workspace'),
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='admins',
        ),
        migrations.AddField(
            model_name='workspace',
            name='admins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
