# Generated by Django 6.0.5 on 2026-05-30 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_remove_workspace_projects_alter_project_work_space_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField()),
                ('revoked', models.BooleanField(default=False)),
                ('no_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_token', to='workspace.workspace')),
            ],
            options={
                'db_table': 'invite_token',
            },
        ),
        migrations.CreateModel(
            name='InviteTokenAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('token created', 'Token Created'), ('token used', 'Token Used'), ('token revoked', 'Token Revoked')], default='token created', max_length=200)),
                ('time', models.DateTimeField(auto_now=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_log', to='workspace.invitetoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_token_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
    ]
