# Generated by Django 6.0.5 on 2026-05-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_invitetoken_invitetokenauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitetoken',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
