# Generated by Django 6.0.5 on 2026-06-03 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_inviterequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inviterequest',
            constraint=models.UniqueConstraint(fields=('pending_user', 'workspace'), name='unique_workspace_request'),
        ),
    ]
