# Generated by Django 6.0.5 on 2026-06-07 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_inviterequest_unique_workspace_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memberbership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')])),
            ],
            options={
                'db_table': 'membership',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='work_space',
        ),
        migrations.RemoveField(
            model_name='fileattachment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='fileattachment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='fileattachment',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='fileattachment',
            name='work_space',
        ),
        migrations.RemoveConstraint(
            model_name='inviterequest',
            name='unique_workspace_request',
        ),
        migrations.RemoveField(
            model_name='invitetoken',
            name='work_space',
        ),
        migrations.RemoveField(
            model_name='invitetokenauditlog',
            name='token',
        ),
        migrations.RemoveField(
            model_name='invitetokenauditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.RemoveField(
            model_name='project',
            name='work_space',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='members',
        ),
        migrations.RemoveField(
            model_name='task',
            name='work_space',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='members',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='super_admin',
        ),
        migrations.AddField(
            model_name='memberbership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_membershitp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberbership',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='workspace.workspace'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='FileAttachment',
        ),
        migrations.RemoveField(
            model_name='inviterequest',
            name='pending_user',
        ),
        migrations.RemoveField(
            model_name='inviterequest',
            name='project',
        ),
        migrations.RemoveField(
            model_name='inviterequest',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='InviteToken',
        ),
        migrations.DeleteModel(
            name='InviteTokenAuditLog',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='InviteRequest',
        ),
    ]
