# Generated by Django 6.0.5 on 2026-06-09 11:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Memberbership',
            new_name='Membership',
        ),
    ]
