# Generated by Django 6.0.5 on 2026-06-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0013_invitetoken_invitetokenauditlog_task_fileattachment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='work_space',
            new_name='workspace',
        ),
    ]
