# Generated by Django 6.0.5 on 2026-06-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0014_rename_work_space_project_workspace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='work_space',
            new_name='workspace',
        ),
    ]
