# Generated by Django 6.0.5 on 2026-06-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0015_rename_work_space_task_workspace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='work_space',
            new_name='workspace',
        ),
        migrations.RenameField(
            model_name='fileattachment',
            old_name='work_space',
            new_name='workspace',
        ),
    ]
