# Generated by Django 6.0.5 on 2026-08-10 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0017_project_status_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='pending', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invite',
            },
        ),
        migrations.RemoveConstraint(
            model_name='inviterequest',
            name='unique_workspace_request',
        ),
        migrations.AddField(
            model_name='invite',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='workspace.project'),
        ),
        migrations.AddField(
            model_name='invite',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='workspace.invitetoken'),
        ),
        migrations.RemoveField(
            model_name='inviterequest',
            name='pending_user',
        ),
        migrations.RemoveField(
            model_name='inviterequest',
            name='project',
        ),
        migrations.RemoveField(
            model_name='inviterequest',
            name='workspace',
        ),
        migrations.AddConstraint(
            model_name='invite',
            constraint=models.UniqueConstraint(fields=('invited_by', 'project'), name='unique_project_request'),
        ),
        migrations.DeleteModel(
            name='InviteRequest',
        ),
    ]
