# Generated by Django 6.0.5 on 2026-08-10 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0018_invite_remove_inviterequest_unique_workspace_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_invite', to='workspace.project'),
        ),
    ]
