# Generated by Django 6.0.5 on 2026-08-12 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0021_alter_project_admins_alter_project_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='admins',
            field=models.ManyToManyField(related_name='task_admins', to='workspace.membership'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_creator', to='workspace.membership'),
        ),
        migrations.AlterField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(related_name='task_members', to='workspace.membership'),
        ),
    ]
