# Generated by Django 6.0.5 on 2026-08-13 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0022_alter_task_admins_alter_task_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
