# Generated by Django 6.0.5 on 2026-08-13 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0024_remove_invite_unique_project_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=200)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_project', to='workspace.membership')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='workspace.project')),
            ],
        ),
    ]
