# Generated by Django 6.0.5 on 2026-08-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0025_remove_project_admins_remove_project_members_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'members'), name='unique_project_membership'),
        ),
        migrations.AlterModelTable(
            name='projectmember',
            table='project_member',
        ),
    ]
