# Generated by Django 6.0.5 on 2026-08-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0026_projectmember_unique_project_membership_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectmember',
            name='unique_project_membership',
        ),
        migrations.RenameField(
            model_name='projectmember',
            old_name='members',
            new_name='member',
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'member'), name='unique_project_membership'),
        ),
    ]
