# Generated by Django 6.0.5 on 2026-08-14 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0027_remove_projectmember_unique_project_membership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_member', to='workspace.project'),
        ),
    ]
