# Generated by Django 6.0.5 on 2026-08-14 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0028_alter_projectmember_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite', to='workspace.membership'),
        ),
    ]
