# Generated by Django 6.0.5 on 2026-08-14 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0029_alter_invite_invited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_user', to='workspace.membership'),
        ),
        migrations.AlterField(
            model_name='invitetokenauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_token_user', to='workspace.membership'),
        ),
    ]
