# Generated by Django 6.0.5 on 2026-08-14 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0031_alter_activitylog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitetokenauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_token_user', to='workspace.membership'),
        ),
    ]
