# Generated by Django 6.0.5 on 2026-08-16 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0032_alter_invitetokenauditlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='task',
            name='members',
        ),
        migrations.AddField(
            model_name='task',
            name='check_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('normal', 'Normal'), ('medium', 'Medium')], default='normal', max_length=100),
        ),
        migrations.CreateModel(
            name='TaskMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=200)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_task', to='workspace.membership')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_member', to='workspace.project')),
            ],
            options={
                'db_table': 'task_member',
                'constraints': [models.UniqueConstraint(fields=('task', 'member'), name='unique_task_membership')],
            },
        ),
    ]
