# Generated by Django 6.0.5 on 2026-08-17 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0033_remove_task_admins_remove_task_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmember',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_member', to='workspace.task'),
        ),
    ]
