# Generated by Django 6.0.5 on 2026-08-25 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0035_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_activity', to='workspace.task'),
        ),
    ]
