# Generated by Django 6.0.5 on 2026-08-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0036_rename_created_at_activitylog_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='user',
            new_name='member',
        ),
    ]
