# Generated by Django 6.0.5 on 2026-08-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0037_rename_user_activitylog_member'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activitylog',
            table='activity_log',
        ),
    ]
