# Generated by Django 6.0.5 on 2026-08-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        ('workspace', '0035_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ManyToManyField(related_name='notification', to='workspace.membership'),
        ),
    ]
