# Generated by Django 6.0.5 on 2026-08-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notification_user_notification_user'),
        ('workspace', '0035_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.ManyToManyField(related_name='read_member', to='workspace.membership'),
        ),
    ]
