# Generated by Django 6.0.5 on 2026-08-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notification_read_notification_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='read_by',
        ),
    ]
