# Generated by Django 6.0.5 on 2026-05-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileattachment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='fileattachment',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='work_space',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='members',
        ),
        migrations.RemoveField(
            model_name='task',
            name='work_space',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='member',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='super_admin',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='FileAttachment',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='WorkSpace',
        ),
    ]
