# Generated by Django 6.0.5 on 2026-09-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_name',
        ),
    ]
